### ISSUE TITLE
[Newbie Question] Does this structure fits projects of any size?

### ISSUE THREAD

**Issue by sinetodev** [LukaszKokot/go-clean-template#2]
First of all, thanks for [this](https://kumojin.com/en/anatomy-golang-app-a-clean-architecture/) excellent article. Helps me a lot. And sorry if my English is not so good.

So, is this structure still enough if a project grows in size? 
I've seen something like `repository`, `usecase`, `ports`, and `models` separated by feature or by an entity.
```
- pkg
    - user
        - model
        - ports
        - repository/storage
        - usecase
    - article
        - model
        ...
```
What do you think about that?

Thanks in advance for you answer!

**Comment by LukaszKokot** [comment]
Hello @sinetodev, for biggest projects, what you described is exactly what we try to do: split across contexts and group model, ports, repositories and usecases together.
In more complex situations, you might even end up with [bounded contexts](https://martinfowler.com/bliki/BoundedContext.html), that is usecases where two different "features" talk to each other.

**Comment by sinetodev** [comment]
Hey @LukaszKokot, thank you for your answer!

If I may share, I found an article that fits well with the tips you gave me.
[Domain Driven Design in Golang - Strategic Design](https://www.damianopetrungaro.com/posts/ddd-using-golang-strategic-design/).

:raising_hand_man:

**Comment by LukaszKokot** [comment]
Thanks @sinetodev, interesting article!
